codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

flags:
  backend:
    paths:
      - backend/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "backend/api/generated/**"
  - "backend/internal/db/sqlc/gen/**"
  - "backend/cmd/**"
  - "**/*.pb.go"
  - "**/*.pb.gw.go"
  - "backend/internal/server/**"
  - "backend/internal/*/domain/**"
  - "backend/internal/*/repository/**"
